name: zkteco
description: A starting point for Dart libraries or applications.
version: 1.0.0

repository: https://github.com/ArishSultan/zkteco_dart.git

environment:
  sdk: ^3.5.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
